// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkUGvja82gEhGTGKdy8jFamMtJInAOzuA',
    appId: '1:1031393190985:web:424b86402b13acdc4fcb98',
    messagingSenderId: '1031393190985',
    projectId: 'exam-ed5dc',
    authDomain: 'exam-ed5dc.firebaseapp.com',
    storageBucket: 'exam-ed5dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIVmkQWi0MkSaUgzD5z9w7dBmN-dYUwPo',
    appId: '1:1031393190985:android:7bd1249336a565cf4fcb98',
    messagingSenderId: '1031393190985',
    projectId: 'exam-ed5dc',
    storageBucket: 'exam-ed5dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeszG8xRnsgyVKH9d33qsVUe5FLMcBNuY',
    appId: '1:1031393190985:ios:9872699d107446c34fcb98',
    messagingSenderId: '1031393190985',
    projectId: 'exam-ed5dc',
    storageBucket: 'exam-ed5dc.appspot.com',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeszG8xRnsgyVKH9d33qsVUe5FLMcBNuY',
    appId: '1:1031393190985:ios:9872699d107446c34fcb98',
    messagingSenderId: '1031393190985',
    projectId: 'exam-ed5dc',
    storageBucket: 'exam-ed5dc.appspot.com',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkUGvja82gEhGTGKdy8jFamMtJInAOzuA',
    appId: '1:1031393190985:web:a979aba35d90a3e64fcb98',
    messagingSenderId: '1031393190985',
    projectId: 'exam-ed5dc',
    authDomain: 'exam-ed5dc.firebaseapp.com',
    storageBucket: 'exam-ed5dc.appspot.com',
  );
}
